version: '3'

services:
  # Новый сервис с простым HTTP-сервером на Node.js
  simple_http_node:
    build:
      context: ./benchmark-suites/node/http
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - PORT=3000

  # Новый сервис для асинхронного бенчмарка на Node.js
  simple_async_node:
    build:
      context: ./benchmark-suites/node/async
      dockerfile: Dockerfile
    ports:
      - "3101:3000"
    environment:
      - PORT=3000
      - PARALLEL_TASKS=10
      - FILE_OPERATION_SIZE=262144
      - DELAY_MS=50
    volumes:
      - ./benchmark-suites/node/async:/app/src
      - /tmp:/tmp
    command: node /app/src/index.js

  # Новый сервис с простым HTTP-сервером на Deno
  simple_http_deno:
    build:
      context: ./benchmark-suites/deno/http
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  # Новый сервис для асинхронного бенчмарка на Deno
  simple_async_deno:
    build:
      context: ./benchmark-suites/deno/async
      dockerfile: Dockerfile
    ports:
      - "3102:3000"
    environment:
      - PORT=3000
      - PARALLEL_TASKS=10
      - FILE_OPERATION_SIZE=262144
      - DELAY_MS=50
    volumes:
      - ./benchmark-suites/deno/async:/app/src
      - /tmp:/tmp
    command: deno run --allow-net --allow-env --allow-read --allow-write /app/src/index.js

  # Новый сервис с простым HTTP-сервером на Bun
  simple_http_bun:
    build:
      context: ./benchmark-suites/bun/http
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003

  # Новый сервис для асинхронного бенчмарка на Bun
  simple_async_bun:
    build:
      context: ./benchmark-suites/bun/async
      dockerfile: Dockerfile
    ports:
      - "3103:3000"
    environment:
      - PORT=3000
      - PARALLEL_TASKS=10
      - FILE_OPERATION_SIZE=262144
      - DELAY_MS=50
    volumes:
      - ./benchmark-suites/bun/async:/app/src
      - /tmp:/tmp
    command: bun run /app/src/index.js
